title: Jiaqi Li's personal Homepage
page-top-title: Jiaqi Li
top-section-bg-text: Electronic Information Engineering
Information and Communication Engineering
home-subtitle: Jiaqi Li&ensp;|&ensp;
copyright-text: '&copy; Jiaqi Li 2024-2025. All Rights Reserved.'
 