title: Jiaqi Li's personal Homepage
page-top-title: 李家奇
top-section-bg-text: 本科：电子信息工程Electronic Information Engineering
研究生：信息与通信工程Information and Communication Engineering
home-subtitle: Jiaqi Li&ensp;|&ensp;李家奇
copyright-text: '&copy; Jiaqi Li 2024-2025. All Rights Reserved.'
 